import ReactQueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GlobalAlert } from "@/components/ui/global-alert";
import { Toaster } from "@/components/ui/sonner";
import { AlertProvider } from "@/context/alert-context";
import { AuthProvider } from "@/context/auth-context";
import { CartProvider } from "@/context/cart-context";
import { ConfigProvider } from "@/context/config-context";
import { ErrorProvider } from "@/context/error-context";
import { LocationProvider } from "@/context/location-context";
import { LOVProvider } from "@/context/lov-context";
import { OrderProvider } from "@/context/order-context";
import { RestaurantFiltersProvider } from "@/context/restaurant-filter-context";
import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Script from "next/script";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Kalida",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script id="fb-sdk-init" strategy="afterInteractive">
        {`
          window.fbAsyncInit = function() {
            FB.init({
              appId      : ${process.env.FACEBOOK_ID},
              xfbml      : true,
              version    : 'v22.0'
            });
          };
        `}
      </Script>

      {/* Facebook SDK script */}
      <Script
        strategy="afterInteractive"
        async
        defer
        crossOrigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js"
      />
      <body
        suppressHydrationWarning
        className={`${openSans.variable} font-sans antialiased`}
      >
        <ReactQueryProvider>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID ?? ""}>
            <RestaurantFiltersProvider>
              <LocationProvider>
                <LOVProvider>
                  <CartProvider>
                    <AuthProvider>
                      <AlertProvider>
                        <OrderProvider>
                          <ConfigProvider>
                            <ErrorProvider>
                              <ThemeProvider
                                attribute="class"
                                defaultTheme="light"
                                enableSystem
                                disableTransitionOnChange
                              >
                                {children}
                                <Toaster />
                                <GlobalAlert />
                              </ThemeProvider>
                            </ErrorProvider>
                          </ConfigProvider>
                        </OrderProvider>
                      </AlertProvider>
                    </AuthProvider>
                  </CartProvider>
                </LOVProvider>
              </LocationProvider>
            </RestaurantFiltersProvider>
          </GoogleOAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
