export const QUERY_KEYS = {
  USERS: "users",
  USER_DETAIL: "user-detail",
  MENU: "menu",
  ALL_MENUS: "all-menus",
  STORE_MENUS: "store-menus",
  UNITS: "units",
  FILTERED_STORES: "filtered_store",
  STORE: "store",
  TABLES: "tables",
  CONFIG: "config",
  LOVS: "lovs",
  ORDERS: "orders",
  ORDER_DETAIL: "order-detail",
  IP_INFO: "ip-info",
  ADDRESS: "address",
  ADDRESS_LIST: "address-list",
  DISTANCE: "distance",
  DEALS: "deals",
  REVIEWS: "reviews",
  DEAL_DETAIL: "deal-detail",
  PAYMENT_GATEWAYS: "payment-gateways",
};
